R4_GAME_CARD_ENABLED=1
R4_GAME_CARD_LABEL=R4CARD
R4_GAME_CARD_UUID=
R4_GAME_CARD_PRIVATE_MOUNTPOINT=/userdata/system/r4/game-card
R4_GAME_CARD_ROMS_MOUNTPOINT=/userdata/roms/r4-card
R4_GAME_CARD_SCREENSHOTS_MOUNTPOINT=/userdata/screenshots/r4-card
R4_GAME_CARD_VIDEOS_MOUNTPOINT=/userdata/recordings/r4-card
R4_GAME_CARD_POLL_INTERVAL=1
